version: '2'
services:
  server:
    image: drone/drone:0.8.2
    environment:
      DRONE_DEBUG: 'false'
      DRONE_GITHUB: 'true'
      DRONE_GITHUB_CLIENT: 85db9ec8d1f6213a16ea
      DRONE_GITHUB_SECRET: 1fa6373c67be6eb3d1417aaa169db9109e8db9b0
      DRONE_HOST: http://drone.hvt.zone
      DRONE_OPEN: 'true'
      DRONE_SECRET: '@sUM]mSV@T{11nF0'
      GIN_MODE: release
      NO_PROXY: drone
      no_proxy: drone
    volumes_from:
    - server-volume
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.sidekicks: server-volume
      io.rancher.container.hostname_override: container_name
  agent:
    image: drone/agent:0.8.2
    environment:
      DRONE_SECRET: '@sUM]mSV@T{11nF0'
      DRONE_SERVER: drone:9000
      NO_PROXY: drone
      no_proxy: drone
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    links:
    - server:drone
    command:
    - agent
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  server-volume:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '0'
      SERVICE_UID: '0'
      SERVICE_VOLUME: /var/lib/drone
    network_mode: none
    volumes:
    - /var/lib/drone
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
