version: '2'
services:
  backend:
    image: hvt1/featureforecast-backend
    environment:
      FEATUREFORECAST_BACKEND_DATABASEPATH: /mnt
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  frontend:
    image: hvt1/featureforecast-frontend
    environment:
      REACT_APP_BACKEND_URL: http://featureforecast-backend.hvt.zone
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
